### ISSUE TITLE
DataBase need some modifications

### ISSUE THREAD

**Issue by sqrt-negativeone** [HamzaBht/Project_JAVA_EE#2]
An aircraft can have multiple cabins, with the current DB design to implement this we need to insert for each cabin type almost the same flight with a different cabin id.

To prevent these redundancies we can add an `Aircraft` table that will represent the different Aircrafts we have, a `CabineClass` table that serves as an enumeration of the possible cabin types, and finally, we need to change the `Cabin` table to have a fk to `aircraft`, a fk to `CabinClass`, and a `capacity `and `availablePlaces` columns.

**Comment by HamzaBht** [comment]
I just have supposed that an aircraft has only one cabin to keep things simple because the second system is only needed for creating an API for demonstration purposes since we didn't find any available API to use in our main project.
and I'm not even sure if there is aircraft with 2 or more cabins. we need to ask @Hafsabougtib.
